### ISSUE TITLE
only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by glevinzon** [5punk/react-slack-chat#16]
React + Redux Starter Kit

**Comment by 5punk** [comment]
@glevinzon 
Can I see a screenshot?

**Comment by 5punk** [comment]
You are absolutely right.

It was added as a patch when users reported polyfill to be absent.

The host app is expected to provide it's own babel-polyfill, just as it is expected to provide React and ReactDOM.

Thank you for the report.
I will remove the production `babel-polyfill` and update the documentation.

**Comment by glevinzon** [comment]
nice, thank you for the fix :+1:

**Comment by trungly** [comment]
@5punk, can you push the 1.8.1 release? I'm not seeing it in https://github.com/5punk/react-slack-chat/releases

Thanks!

**Comment by 5punk** [comment]
@trungly 
`v1.8.0` should work, please confirm.

**Comment by trungly** [comment]
You're right!  I tried this with a brand new app created from `create-react-app`(1.4.0) and it works!     No `regeneratorRuntime is not defined` error this time.

Another thing I realized is that in order to correctly join a channel from the chat widget, I needed to create a Custom Bot (under Custom Integrations), not an App Bot in Slack.  I never knew about this distinction.  Hope that helps anyone else that is running into same problem I had (i.e. "mising_scope" error on the channels.history XHR request).
