### ISSUE TITLE
Got 404 on svg file

### ISSUE THREAD

**Issue by hug33k** [5punk/react-slack-chat#9]
When I'm trying to load my webpage, I have this error :
`GET http://localhost:8080/ba0f1995c4ef43b1af1eb2588310eb5c.svg 404 (Not Found)`

Using `grep`, I found this filename in `node_modules/react-slack-chat/dist/react-slack-chat.js`.

Do you already had this error one time? Or maybe it can be related to my Webpack config...

**Comment by 5punk** [comment]
@hug33k 
Confirmed bug.

Fixed in `v1.3.0`.

Could you please update to the latest. Let me know?

I just did a fresh install of `react-slack-chat@v1.3.0` on a brand new cloned [example react app](https://github.com/mzabriskie/react-example). It worked out of the box with `v1.3.0`.

It works perfectly.
![image](https://cloud.githubusercontent.com/assets/8335261/23193307/1951f66a-f85d-11e6-9204-e461e41b4f20.png)

**Comment by hug33k** [comment]
It works !
Is it possible to change this icon using properties of the component ?

**Comment by 5punk** [comment]
Sure, that can be a feature request.
Add another issue for that request, I will get on it tomorrow.
